#!/usr/bin/env python3
"""Emit compact DMA outlines for the website's coverage map.

Converts the research TopoJSON (simzou/nielsen-dma nielsentopo.json) into
minified TopoJSON keyed by DMA code, so the browser can shade each television
market by how likely a given game is to air there.

Why TopoJSON rather than GeoJSON: adjacent DMAs share borders, and TopoJSON
stores each shared border once. Converting to GeoJSON duplicates every internal
boundary and roughly triples the payload.

The source file is already compact once whitespace is dropped (~162 KB, ~52 KB
gzipped). Simplification was measured and rejected: at a tolerance aggressive
enough to matter visually it saved only ~9 KB gzipped, which is not worth the
coastline damage.

PROVENANCE: these boundaries are Nielsen-derived and redistributed by a public
repository. Fine for research and this prototype, but review licensing before
treating the shapes as production data or publishing them widely.

Usage
-----
py .\tools\build_map_geometry.py --output .\data\dma-geometry.json
"""
from __future__ import annotations

import argparse
import gzip
import json
import sys
from pathlib import Path
from typing import Any


def log(msg: str) -> None:
    print(msg, file=sys.stderr, flush=True)


def build(src: Path) -> dict[str, Any]:
    topo = json.loads(src.read_text(encoding="utf-8"))
    if topo.get("type") != "Topology":
        raise SystemExit(f"{src} is not TopoJSON (type={topo.get('type')!r})")

    objects = topo.get("objects") or {}
    if "nielsen_dma" not in objects:
        raise SystemExit(f"expected a 'nielsen_dma' object, found {list(objects)}")

    geoms = objects["nielsen_dma"].get("geometries", [])
    kept: list[dict[str, Any]] = []
    names: dict[str, str] = {}
    centroids: dict[str, list[float]] = {}

    for g in geoms:
        props = g.get("properties") or {}
        code = g.get("id") or props.get("dma")
        if code is None:
            continue
        code = str(code)
        name = props.get("dma1") or props.get("name") or f"DMA {code}"
        names[code] = name
        lat, lon = props.get("latitude"), props.get("longitude")
        if isinstance(lat, (int, float)) and isinstance(lon, (int, float)):
            # Rounded: this is only used to place map labels/tooltips.
            centroids[code] = [round(float(lon), 3), round(float(lat), 3)]
        # Drop the per-DMA demographic properties the map does not use
        # (tvperc/cableperc/adsperc) and keep the code as the sole identifier.
        kept.append({"type": g["type"], "id": code, "arcs": g["arcs"]})

    out = {
        "type": "Topology",
        "transform": topo["transform"],
        "arcs": topo["arcs"],
        "objects": {"dma": {"type": "GeometryCollection", "geometries": kept}},
        "dma_names": names,
        "dma_centroids": centroids,
        "provenance": (
            "Nielsen-derived DMA boundaries via the public simzou/nielsen-dma "
            "dataset. Research/prototype use; review licensing before wider "
            "redistribution."
        ),
    }
    log(f"{len(kept)} DMA geometries, {len(topo['arcs'])} arcs, "
        f"{sum(len(a) for a in topo['arcs'])} arc points")
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--source", type=Path, default=Path("tools/nielsentopo.json"))
    p.add_argument("--output", type=Path, default=Path("data/dma-geometry.json"))
    p.add_argument("--js", type=Path, default=None)
    args = p.parse_args()

    if not args.source.exists():
        p.error(f"Not found: {args.source}")

    payload = build(args.source)
    blob = json.dumps(payload, separators=(",", ":"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(blob, encoding="utf-8")

    raw = len(blob.encode("utf-8"))
    gz = len(gzip.compress(blob.encode("utf-8"), 9))
    print(f"Wrote {args.output}")
    print(f"  source  : {args.source.stat().st_size/1e6:8.3f} MB")
    print(f"  minified: {raw/1e6:8.3f} MB")
    print(f"  gzipped : {gz/1e6:8.3f} MB  (what Pages serves)")

    if args.js:
        args.js.write_text(
            "/* Generated by tools/build_map_geometry.py. Do not edit by hand. */\n"
            f"window.NFL_DMA_GEO={blob};\n", encoding="utf-8")
        print(f"Wrote {args.js}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
