"""Build a compact ZIP -> IANA timezone table for the web app.

Source is the same curated-us-zips CSV the local-market resolver already uses
for centroids, which carries an authoritative per-ZIP `timezone` column. Using
it here means no new data dependency.

Compaction: US ZIPs are heavily clustered by timezone, so store one entry per
3-digit prefix when the whole prefix agrees, and fall back to explicit 5-digit
entries only for the prefixes that straddle a zone boundary. That turns ~33k
rows into a few KB while staying exact.

Output: zip-timezones.js defining window.NFL_ZIP_TZ.
"""
import csv, io, json, os, sys, urllib.request
from collections import defaultdict, Counter

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SRC = "https://raw.githubusercontent.com/ReadyAPIs-com/curated-us-zips/main/data/us-zips.csv"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "zip-timezones.js")

try:  # corporate TLS interception: trust the OS store, as the other tools do
    import truststore
    truststore.inject_into_ssl()
except Exception as exc:  # pragma: no cover - environment dependent
    print(f"note: truststore unavailable ({exc}); using default TLS chain")


def fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=180) as r:
        return r.read().decode("utf-8", "replace")


def main() -> int:
    rows = list(csv.DictReader(io.StringIO(fetch(SRC))))
    print(f"source rows: {len(rows)}")

    by_zip = {}
    for row in rows:
        zip_code = (row.get("zip_code") or "").strip().zfill(5)
        tz = (row.get("timezone") or "").strip()
        if len(zip_code) == 5 and zip_code.isdigit() and tz:
            by_zip[zip_code] = tz
    print(f"zips with a timezone: {len(by_zip)}")
    print("distinct zones:", len(set(by_zip.values())))
    for tz, n in Counter(by_zip.values()).most_common():
        print(f"  {tz:26s} {n}")

    # Group by 3-digit prefix; a prefix is "pure" when every ZIP in it agrees.
    groups = defaultdict(set)
    for zip_code, tz in by_zip.items():
        groups[zip_code[:3]].add(tz)

    prefixes, exceptions = {}, {}
    mixed = 0
    for prefix, zones in sorted(groups.items()):
        if len(zones) == 1:
            prefixes[prefix] = next(iter(zones))
            continue
        mixed += 1
        # Majority zone covers the prefix; list only the ZIPs that differ.
        counts = Counter(tz for z, tz in by_zip.items() if z.startswith(prefix))
        major = counts.most_common(1)[0][0]
        prefixes[prefix] = major
        for zip_code, tz in by_zip.items():
            if zip_code.startswith(prefix) and tz != major:
                exceptions[zip_code] = tz

    print(f"\nprefixes: {len(prefixes)}  (mixed-zone prefixes: {mixed})")
    print(f"explicit 5-digit exceptions: {len(exceptions)}")

    # Intern zone names so the payload stores small indices, not repeated strings.
    zones = sorted({*prefixes.values(), *exceptions.values()})
    zi = {z: i for i, z in enumerate(zones)}
    payload = {
        "zones": zones,
        "prefix": {p: zi[z] for p, z in sorted(prefixes.items())},
        "exact": {z: zi[t] for z, t in sorted(exceptions.items())},
    }

    body = json.dumps(payload, separators=(",", ":"))
    js = (
        "/* Generated by tools/build_zip_timezones.py. Do not edit by hand.\n"
        "   ZIP -> IANA timezone. Stored as 3-digit prefixes with explicit\n"
        "   5-digit exceptions for the prefixes that straddle a zone boundary. */\n"
        f"window.NFL_ZIP_TZ={body};\n"
    )
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(js)

    size = os.path.getsize(OUT)
    print(f"\nwrote {OUT}  ({size/1024:.1f} KB)")

    # Verify: every source ZIP must resolve back to its true zone.
    def lookup(zip_code: str):
        if zip_code in payload["exact"]:
            return zones[payload["exact"][zip_code]]
        idx = payload["prefix"].get(zip_code[:3])
        return zones[idx] if idx is not None else None

    bad = [(z, tz, lookup(z)) for z, tz in by_zip.items() if lookup(z) != tz]
    print(f"round-trip check: {len(by_zip) - len(bad)}/{len(by_zip)} exact"
          + (" — LOSSLESS" if not bad else ""))
    for z, want, got in bad[:10]:
        print(f"  MISMATCH {z}: want {want} got {got}")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
