"""Build a compact Sleeper player-id -> name/position/team map.

Sleeper's roster endpoints return only numeric player ids, and its own player
dictionary (/players/nfl) is ~14 MB -- far too large to ship or to fetch in the
browser (Sleeper also asks that it be pulled at most once a day). This trims it
to players who can actually appear in a lineup and emits a small lookup file.

The app matches these names against the projections already in fantasy-data.js,
so the output only needs enough to identify a player: name, position, team.

Output: sleeper-ids.js defining window.NFL_SLEEPER_IDS.
"""
from __future__ import annotations

import io
import json
import os
import sys
import urllib.request

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SRC = "https://api.sleeper.app/v1/players/nfl"
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "sleeper-ids.js")

# Positions that can occupy a lineup slot in this app. Sleeper also carries
# offensive linemen, coaches and long-snappers, which no fantasy lineup uses.
KEEP_POSITIONS = {"QB", "RB", "WR", "TE", "K", "DEF"}

# Sleeper uses a few team codes that differ from the schedule data in
# index.html. Normalise so name+team matching lines up.
TEAM_ALIAS = {"WSH": "WAS", "JAC": "JAX", "LA": "LAR", "OAK": "LV", "SD": "LAC"}

# The app labels team defences by mascot; build that from index.html's own
# TEAM_NAMES so the two can never drift apart.
def _load_def_names() -> dict[str, str]:
    import json as _json
    import re as _re
    path = os.path.join(REPO, "index.html")
    src = io.open(path, encoding="utf-8").read()
    m = _re.search(r"const TEAM_NAMES=(\{.*?\});", src, _re.S)
    if not m:
        return {}
    names = _json.loads(m.group(1))
    return {code: full.split()[-1] + " D/ST" for code, full in names.items()}

DEF_NAME = _load_def_names()

try:  # corporate TLS interception: trust the OS store, as the other tools do
    import truststore
    truststore.inject_into_ssl()
except Exception as exc:  # pragma: no cover - environment dependent
    print(f"note: truststore unavailable ({exc}); using the default TLS chain")


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=240) as r:
        return r.read()


def main() -> int:
    raw = fetch(SRC)
    print(f"source: {len(raw)/1024/1024:.2f} MB")
    players = json.loads(raw.decode("utf-8"))
    print(f"entries: {len(players)}")

    kept = {}
    skipped_no_team = 0
    for pid, p in players.items():
        pos = p.get("position")
        if pos not in KEEP_POSITIONS:
            continue
        team = p.get("team")
        if not team:
            # Free agents cannot be in a game this week, so they cannot match a
            # matchup. Keep them out; an imported roster slot for a free agent
            # simply will not resolve, which is the honest outcome.
            skipped_no_team += 1
            continue
        team = TEAM_ALIAS.get(team, team)
        name = p.get("full_name")
        if not name:
            # Team defences have no full_name. Sleeper keys them by team code,
            # but this app names them by mascot ("Lions D/ST"), so translate --
            # otherwise every D/ST import fails to resolve.
            if pos == "DEF":
                name = DEF_NAME.get(team, f"{team} D/ST")
            else:
                first = (p.get("first_name") or "").strip()
                last = (p.get("last_name") or "").strip()
                name = (first + " " + last).strip()
        if not name:
            continue
        # Store as a 3-tuple array rather than an object: same information,
        # roughly 40% smaller once repeated across ~900 entries.
        kept[str(pid)] = [name, pos, team]

    print(f"kept: {len(kept)}  (dropped {skipped_no_team} without an NFL team)")
    by_pos: dict[str, int] = {}
    for _n, pos, _t in kept.values():
        by_pos[pos] = by_pos.get(pos, 0) + 1
    for pos in sorted(by_pos, key=lambda k: -by_pos[k]):
        print(f"  {pos:4s} {by_pos[pos]}")

    body = json.dumps(kept, separators=(",", ":"), sort_keys=True)
    js = (
        "/* Generated by tools/build_sleeper_ids.py. Do not edit by hand.\n"
        "   Sleeper player id -> [name, position, team]. Trimmed from Sleeper's\n"
        "   ~14 MB /players/nfl dictionary to players who can fill a lineup slot.\n"
        "   Regenerate when rosters change (Sleeper asks for at most daily). */\n"
        f"window.NFL_SLEEPER_IDS={body};\n"
    )
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(js)
    size = os.path.getsize(OUT)
    print(f"\nwrote {OUT}  ({size/1024:.1f} KB)")

    # Sanity: a few known ids must resolve.
    checks = {"4046": "Patrick Mahomes", "11563": "Bo Nix", "5846": "DK Metcalf"}
    bad = [(k, v, kept.get(k)) for k, v in checks.items()
           if not kept.get(k) or kept[k][0] != v]
    if bad:
        for k, want, got in bad:
            print(f"  CHECK FAILED {k}: want {want} got {got}")
        return 1
    print("spot checks passed:", ", ".join(f"{k}={kept[k][0]}" for k in checks))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
